var app=angular.module('ionicApp',['ionic'])
     app.config(function($stateProvider,$urlRouterProvider){
     	
     	$stateProvider
     	 .state('home',{
     	 	url:"/home",
     	 	templateUrl:"tpl/home/index.html"
     	})
     	 .state('facts',{
     	 	url:"/facts",
     	 	templateUrl:"tpl/info/facts.html"
     	 })
     	 .state('process',{
     	 	url:"/process",
     	 	templateUrl:"tpl/info/process.html"
     	 })
     	 .state('payment',{
     	 	url:"/payment",
     	 	templateUrl:"tpl/info/payment.html"
     	 })
     	 .state('use',{
     	 	url:"/use",
     	 	templateUrl:"tpl/info/use.html"
     	 })
     	 .state('voucher',{
     	 	url:"/voucher",
     	 	templateUrl:"tpl/info/voucher.html"
     	 })
     	 .state('cty',{
     	 	url:"/cty",
     	 	templateUrl:"tpl/info/cty.html"
     	 })
     	 .state('rem',{
     	 	url:"/rem",
     	 	templateUrl:"tpl/info/rem.html"
     	 })
     	 .state('policy',{
     	 	url:"/policy",
     	 	templateUrl:"tpl/info/policy.html"
     	 })
     	 $urlRouterProvider.otherwise("/home");
     	 
     })
