var app=angular.module('ionicApp',['ionic'])
	app.config(function($stateProvider,$urlRouterProvider){
		$stateProvider
		.state('home',{
			url:"/home",
			templateUrl:"tpl/home/index.html"
		})
		.state('facts',{
			url:"/facts",
			templateUrl:"tpl/info/facts.html"
		})
		.state('sach',{
			url:"/sach",
			templateUrl:"tpl/info/sach.html"
		})
		.state('report',{
			url:"/report",
			templateUrl:"tpl/info/report.html"
		})
		.state('delivery',{
			url:"/delivery",
			templateUrl:"tpl/info/delivery.html"
		})
		.state('Store',{
			url:"/Store",
			templateUrl:"tpl/info/Store.html"
		})
		.state('Admin',{
			url:"/Admin",
			templateUrl:"tpl/info/Admin.html"
		})
		.state('shop',{
			url:"/shop",
			templateUrl:"tpl/info/shop.html"
		})
		.state('extsion',{
			url:"/extsion",
			templateUrl:"tpl/info/extsion.html"
		})
		.state('processing',{
			url:"/processing",
			templateUrl:"tpl/info/processing.html"
		})
		.state('cou',{
			url:"/cou",
			templateUrl:"tpl/info/cou.html"
		})
		.state('set',{
			url:"/set",
			templateUrl:"tpl/info/set.html"
		})
		.state('switch',{
			url:"/switch",
			templateUrl:"tpl/info/switch.html"
		})
		$urlRouterProvider.otherwise("/home");
	})
